

===   [ 收集测试用例 ]  === 


== cases\__st__.py 


== cases\blank_env\__st__.py 


== cases\blank_env\loginAPI.py 


== cases\blank_env\customerAPI\addCustomer.py 


== cases\blank_env\customerAPI\delCustomer.py 


== cases\blank_env\customerAPI\listCustomer.py 


== cases\blank_env\customerAPI\modifyCustomer.py 


== cases\blank_env\medicineAPI\addMedicine.py 


== cases\blank_env\medicineAPI\delMedicine.py 


== cases\blank_env\medicineAPI\listMedicine.py 


== cases\blank_env\medicineAPI\modifyMedicine.py 


== cases\blank_env\oneCustomer_env\__st__.py 


== cases\blank_env\oneCustomer_env\delCustomer.py 


== cases\blank_env\oneCustomer_env\modifyCustomer.py 


== cases\blank_env\oneCustomer_env\oneCustomerOneMedicineOneOrder\__st__.py 


== cases\blank_env\oneCustomer_env\oneCustomerOneMedicineOneOrder\delCustomer.py 


== cases\blank_env\oneCustomer_env\twoCustomers_env\__st__.py 


== cases\blank_env\oneCustomer_env\twoCustomers_env\modifyCustomer.py 


== cases\blank_env\oneCustomer_env\twoCustomers_env\tenCustomers_env\__st__.py 


== cases\blank_env\oneCustomer_env\twoCustomers_env\tenCustomers_env\addCustomer.py 


== cases\blank_env\oneCustomer_env\twoCustomers_env\tenCustomers_env\listCustomer.py 


== cases\blank_env\oneMedicine_env\__st__.py 


== cases\blank_env\oneMedicine_env\delMedicine.py 


== cases\blank_env\oneMedicine_env\modifyMedicine.py 


== cases\blank_env\oneMedicine_env\twoMedicine_env\__st__.py 


== cases\blank_env\oneMedicine_env\twoMedicine_env\modifyMedicine.py 



===   [ 执行测试用例 ]  === 

预备执行用例数量 : 63



  ========= 测试开始 : 20250505_215008 =========



>>> cases\

[ suite setup ] cases\


>>> cases\blank_env\

[ suite setup ] cases\blank_env\

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Set-Cookie: sessionid=txenchq53nz6nmprn1r4b1olmphhr5wu; Path=/; Max-Age=1209600; HttpOnly
Date: Mon, 05 May 2025 13:50:08 GMT
Content-Length: 9

{"ret":0}
-------- HTTP response * end -------

删除所有订单
列出订单

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:08 GMT
Content-Length: 32

{"ret":0,"retlist":[],"total":0}
-------- HTTP response * end -------

删除所有客户
列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:08 GMT
Content-Length: 32

{"ret":0,"retlist":[],"total":0}
-------- HTTP response * end -------

所有药品
列出药品

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:08 GMT
Content-Length: 32

{"ret":0,"retlist":[],"total":0}
-------- HTTP response * end -------



>>> cases\blank_env\loginAPI.py

* 登录-0001  -  2025-05-05 21:50:08

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Set-Cookie: sessionid=1prf095oipzl0uys3fhw5l5fu55va523; Path=/; Max-Age=1209600; HttpOnly
Date: Mon, 05 May 2025 13:50:08 GMT
Content-Length: 9

{"ret":0}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0002  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0003  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0004  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0005  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0006  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0007  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  通过

  PASS 

* 登录-0008  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\loginAPI.py", line 68, in teststeps
    CHECK_POINT('检查返回值', res == ret.json())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 登录-0009  -  2025-05-05 21:50:09

  [ case execution steps ]

-- 第 1 步 -- 登录系统 

登录系统

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:09 GMT
Content-Length: 45

{"msg":"用户名或者密码错误","ret":1}
-------- HTTP response * end -------


** 检查点 **  检查返回值 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\loginAPI.py", line 68, in teststeps
    CHECK_POINT('检查返回值', res == ret.json())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError



>>> cases\blank_env\customerAPI\addCustomer.py

* 添加客户-API-0151  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 添加一个客户 

添加客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 18

{"id":546,"ret":0}
-------- HTTP response * end -------


** 检查点 **  返回的ret值=0 ---->  通过


-- 第 2 步 -- 检查系统数据 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 141

{"ret":0,"retlist":[{"address":"武汉市桥西医院北路","id":546,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":1}
-------- HTTP response * end -------


** 检查点 **  返回的消息体数据正确 ---->  通过

  PASS 

* 添加客户-API-0153  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 添加一个客户 

添加客户

-------- HTTP response * begin -------
400
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 125

{"msg":"req body format error\nKey: 'Body.Data.Name' Error:Field validation for 'Name' failed on the 'required' tag","ret":2}
-------- HTTP response * end -------


** 检查点 **  返回的ret值 ---->  通过


-- 第 2 步 -- 检查系统数据 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 141

{"ret":0,"retlist":[{"address":"武汉市桥西医院北路","id":546,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":1}
-------- HTTP response * end -------


** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\addCustomer.py", line 59, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 添加客户-API-0154  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 添加一个客户 

添加客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 18

{"id":547,"ret":0}
-------- HTTP response * end -------


** 检查点 **  返回的ret值 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\addCustomer.py", line 81, in teststeps
    CHECK_POINT('返回的ret值', addRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 添加客户-API-0155  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 添加一个客户 

添加客户

-------- HTTP response * begin -------
400
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 139

{"msg":"req body format error\nKey: 'Body.Data.Phonenumber' Error:Field validation for 'Phonenumber' failed on the 'required' tag","ret":2}
-------- HTTP response * end -------


** 检查点 **  返回的ret值 ---->  通过


-- 第 2 步 -- 检查系统数据 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 135

{"ret":0,"retlist":[{"address":"南京市鼓楼北路","id":547,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":2}
-------- HTTP response * end -------


** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\addCustomer.py", line 124, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 添加客户-API-0156  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 添加一个客户 

添加客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 18

{"id":548,"ret":0}
-------- HTTP response * end -------


** 检查点 **  返回的ret值 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\addCustomer.py", line 146, in teststeps
    CHECK_POINT('返回的ret值', addRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError



>>> cases\blank_env\customerAPI\delCustomer.py

* 删除客户-API-0251  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 删除一个不存在ID的客户 

删除客户：id=100

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 9

{"ret":0}
-------- HTTP response * end -------


** 检查点 **  返回的ret值=2 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\delCustomer.py", line 13, in teststeps
    CHECK_POINT('返回的ret值=2', addRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError



>>> cases\blank_env\customerAPI\listCustomer.py

* 列出客户-API-0101  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 尝试列出客户，没有携带有效的sessionid 

列出客户

-------- HTTP response * begin -------
307
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 57

{"msg":"未登录","redirect":"/mgr/sign.html","ret":302}
-------- HTTP response * end -------

返回状态码是307
listRet{'msg': '未登录', 'redirect': '/mgr/sign.html', 'ret': 302}

** 检查点 **  返回的消息体数据正确 ---->  通过

  PASS 

* 列出客户-API-0102  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 列出客户 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 349

{"ret":0,"retlist":[{"address":"南京市鼓楼北路","id":548,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"南京市鼓楼北路","id":547,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"武汉市桥西医院北路","id":546,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":3}
-------- HTTP response * end -------


** 检查点 **  检查状态码 ---->  通过


** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\listCustomer.py", line 42, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 列出客户-API-0103  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 列出客户 

列出客户

-------- HTTP response * begin -------
400
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 35

{"msg":"bad pagenum:hello","ret":2}
-------- HTTP response * end -------

状态码:400
listRet{'msg': 'bad pagenum:hello', 'ret': 2}

** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\listCustomer.py", line 60, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 列出客户-API-0104  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 列出客户 

列出客户

-------- HTTP response * begin -------
400
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 36

{"msg":"bad pagesize:hello","ret":2}
-------- HTTP response * end -------

状态码:400
listRet{'msg': 'bad pagesize:hello', 'ret': 2}

** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\listCustomer.py", line 78, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 列出客户-API-0105  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 列出客户 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 349

{"ret":0,"retlist":[{"address":"南京市鼓楼北路","id":548,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"南京市鼓楼北路","id":547,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"武汉市桥西医院北路","id":546,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":3}
-------- HTTP response * end -------

状态码:200
listRet:{'ret': 0, 'retlist': [{'address': '南京市鼓楼北路', 'id': 548, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}, {'address': '南京市鼓楼北路', 'id': 547, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}, {'address': '武汉市桥西医院北路', 'id': 546, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}], 'total': 3}

** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\listCustomer.py", line 96, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 列出客户-API-0106  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 列出客户 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 135

{"ret":0,"retlist":[{"address":"南京市鼓楼北路","id":548,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":3}
-------- HTTP response * end -------

状态码:200
listRet:{'ret': 0, 'retlist': [{'address': '南京市鼓楼北路', 'id': 548, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}], 'total': 3}

** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\listCustomer.py", line 113, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError


* 列出客户-API-0107  -  2025-05-05 21:50:10

  [ case execution steps ]

-- 第 1 步 -- 列出客户 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:10 GMT
Content-Length: 349

{"ret":0,"retlist":[{"address":"南京市鼓楼北路","id":548,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"南京市鼓楼北路","id":547,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"武汉市桥西医院北路","id":546,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":3}
-------- HTTP response * end -------

状态码:200
listRet:{'ret': 0, 'retlist': [{'address': '南京市鼓楼北路', 'id': 548, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}, {'address': '南京市鼓楼北路', 'id': 547, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}, {'address': '武汉市桥西医院北路', 'id': 546, 'name': '武汉市桥西医院', 'phonenumber': '13345679934'}], 'total': 3}

** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\listCustomer.py", line 130, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError



>>> cases\blank_env\customerAPI\modifyCustomer.py

* 修改客户-API-0201  -  2025-05-05 21:50:11

  [ case execution steps ]

-- 第 1 步 -- 修改一个不存在ID的客户 

修改客户

-------- HTTP response * begin -------
400
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:11 GMT
Content-Length: 39

{"msg":"customer id not exist","ret":2}
-------- HTTP response * end -------


** 检查点 **  返回的ret值=2 ---->  通过


-- 第 2 步 -- 检查系统数据 

列出客户

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:11 GMT
Content-Length: 349

{"ret":0,"retlist":[{"address":"南京市鼓楼北路","id":548,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"南京市鼓楼北路","id":547,"name":"武汉市桥西医院","phonenumber":"13345679934"},{"address":"武汉市桥西医院北路","id":546,"name":"武汉市桥西医院","phonenumber":"13345679934"}],"total":3}
-------- HTTP response * end -------


** 检查点 **  返回的消息体数据正确 ---->  !! 不通过!!

  FAIL    
Traceback:
  File "D:\tools\projects\autotest_bysms\cases\blank_env\customerAPI\modifyCustomer.py", line 25, in teststeps
    CHECK_POINT('返回的消息体数据正确', listRet == expected)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\common.py", line 76, in CHECK_POINT
    raise AssertionError()
AssertionError



>>> cases\blank_env\medicineAPI\addMedicine.py

* 添加药品-API-0351  -  2025-05-05 21:50:11

  [ case execution steps ]

-- 第 1 步 -- 添加一个药品 

添加药品

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:11 GMT
Content-Length: 18

{"id":127,"ret":0}
-------- HTTP response * end -------


** 检查点 **  返回的ret值=0 ---->  通过


-- 第 2 步 -- 检查系统数据 

列出药品

-------- HTTP response * begin -------
200
Content-Type: application/json; charset=utf-8
Date: Mon, 05 May 2025 13:50:11 GMT
Content-Length: 110

{"ret":0,"retlist":[{"desc":"青霉素 国字号","id":127,"name":"青霉素","sn":"099877883837"}],"total":1}
-------- HTTP response * end -------


** 检查点 **  返回的消息体数据正确 ---->  通过

  PASS 
  ABORT   'API-0351' 
Traceback:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Lib\site-packages\hytest\utils\signal.py", line 16, in _broadcast
    method(*arg,**kargs)
  File "D:\tools\projects\autotest_bysms\cases\__st__.py", line 59, in case_result
    cell = self.sheet.Cells(self.caseNum2Row[caseNo], self.TEST_RET_COL_NO)
                            ~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'API-0351'

